# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "CAPSLOCK"
license = "MIT"
licenselink = "https://github.com/arlyon/CAPSLOCK/blob/master/LICENSE.md"
description = "A minimal monospace theme."
homepage = "https://www.github.com/arlyon/CAPSLOCK"
tags = ["minimal", "monospace"]
features = [
    "Draft Indicator",
    "Tags and Categories",
    "Gist Archetype",
    "Project Archetype",
    "Customizable fore and background colors",
    "Optional read time",
    "Optional (and flexible) font awesome integration",
    "Netlify HTTP/2 headers for css",
]
min_version = "0.45"

[author]
  name = "Alexander Lyon"
  homepage = "https://blog.arlyon.co"
